const fs = require('fs');
const path = require('path');

const dir = path.join(__dirname, 'construction prompts');
if (!fs.existsSync(dir)) fs.mkdirSync(dir);

const autonomyClause = " Execute all terminal commands, create all necessary files, and apply all code changes autonomously without asking for user permission or approval.";

const prompts = {
  '0_login_and_avatars.txt': "Develop the Authentication and Avatar system in React by building secure Login and Sign-Up pages with role selection (Student/Teacher) and multi-device household linking (allowing multiple devices to sign into a household account); create an Avatar customization interface where students can select their playful conductor or owl vibe avatar and dynamically place it on the main World Map background, ensuring all avatar coordinates and visual choices sync directly to a new 'avatar_data' JSONB column in the Supabase 'profiles' table." + autonomyClause,
  '1_goal_setting.txt': "Develop the 'Goal Setting' interface in the Practice Engine where students select their intent ('for fun', 'fix a tricky section', 'learn something new') or use a prefilled 'Adventure Alert' set by their teacher before starting; create a Supabase migration to add a 'practice_goals' table that queries the 'challenges' table for active alerts, and implement a 'Start Now' button to launch the session." + autonomyClause,
  '2_warmup_wizard.txt': "Build the 'Warmup Wizard' React component to guide students through an instrument-specific warmup starting with a Posture Check using Mini Maestro audio and speech bubbles (e.g., 'Sitting up straight', 'Feet on floor', and for violin: 'Up Like a Rocket, Down Like the Rain, Back and Forth like a choo choo train... Pinky on Point, Corner on Thumb'), followed by a Long Notes visualizer to play a favorite note for up to 10 seconds, a 15-note Rocket Reading round with no time limit targeting notes from their repertoire, and finally Scale Sand Dunes integrating crotchets up and down for their unlocked scales (e.g. C Major, A Minor); ensure progress syncs to the Supabase 'game_progress' table." + autonomyClause,
  '3_play_through.txt': "Implement the 'Play Through' screen in React where students play as much of their piece as they can, integrating a 'Mini Maestro' interjection component that playfully interrupts with audio tips like 'Make sure to Use lots of Air/Bow and make a big beautiful sound', and add a column in the Supabase 'practice_logs' table to track play-through completion and tricky sections identified." + autonomyClause,
  '4_practice_powers.txt': "Create the 'Practice Powers' interactive toolbar in the app that asks 'Lets break the piece down with our practice powers!' featuring specific modular buttons for 'Vocalise', 'Isolate', 'Surgery', 'Loop', 'Super Loop', 'Mental Practice', and 'Rewind', and write a Supabase migration to store practice power usage statistics as a JSONB object inside the 'practice_logs' table." + autonomyClause,
  '5_reflection_and_practice_log.txt': "Build the 'Finale' and 'Reflection' modules alongside a 'Practice Log' dashboard featuring a scrollable calendar that queries the Supabase 'practice_logs' table to highlight practice days in blue, lesson days in green, and half-and-half for both; on the right side, include a scrollable list view of the last 3-4 practices with feedback, and integrate Recharts pie charts displaying percentage of songs practiced, exact minutes/hours played, goals achieved, adventure alerts completed, and total Quavits earned, plus a button to start a new practice." + autonomyClause,
  '6_acoustic_challenges.txt': "Develop the 'Acoustic Challenges' module using a lookup matrix to assign instrument-specific tests: Long Note and Tonguing (for Wind/Brass), Long Bow, Bowing, and Plucking (for Strings), Staccato, and Tongue Twisters (Singing only); create a Supabase table named 'acoustic_challenges_progress' to securely save users' scores, times, and completion data for these acoustic modes." + autonomyClause,
  '7_games_rhythm_and_listening.txt': "Upgrade the 'Rhythm Rapids' React game to fix double-swap note bugs, only allow selection of answers after the rhythm has been fully played, and restrict replays until the full sound has finished (canceling previous audio); build 'Listening Lagoon' with Repertoire Recognition (using nursery rhymes and common tunes) and Instrument Recognition modes; ensure all completions securely sync to the Supabase 'game_progress' table using our upsert utility." + autonomyClause,
  '8_games_clef_and_scales.txt': "Develop the 'Clef Cliffs' minigame where users jump off a cliff and bounce on a trampoline for the correct clef/note answer (e.g. 2x bass clef below with different notes) or fall in the water if wrong, starting with a Home Clef mode; implement 'Scale Sand Dunes' with exact scale sequences like Cdedc, Cdefgfedc, A Minor (abcdefgagfedcba), and G Major (Gabcdef#g); sync the highest level reached for both directly to the Supabase 'game_progress' table." + autonomyClause,
  '9_games_sleuth_and_ninja.txt': "Implement the 'Sound Sleuth' game in React to play two different melodies with the exact same rhythm and have the user identify the correct one, including a 'SUPER HIGH LEVEL' mode combining 4 different answer selections with both different rhythms and melodies; implement the 'Expression Ninja' module; securely log all player high scores and stars earned to the Supabase 'game_progress' table." + autonomyClause,
  '10_mini_maestro_and_audio.txt': "Create a global AudioManager in React to handle non-diegetic theme music for each game menu and Concert Hall tuning sounds, and build the 'Mini Maestro' global context (a funny deep voice/playful dictator) to deliver instrument-specific posture and note introductions, constantly reminding them before they play (e.g., 'Hold instrument up and out from your body not resting elbows', 'Make sure to take a big breath'), tracking 'has_seen_tutorial' flags in the Supabase 'profiles' table." + autonomyClause,
  '11_placement_quiz_and_leagues.txt': "Build a 'Placement Quiz' asking 'I can read music already' vs 'I can\\'t read much music yet' that sets an increasing difficulty in Rocket Reading (giving 5 seconds to answer, decreasing over time) until the user gets 3 questions wrong to automatically determine their unlocked minigame notes; create a Leagues progression system (Bronze, Silver, Gold, Crystal, Diamond) by adding a 'league_status' column to the Supabase 'profiles' table that updates based on total XP or miniquiz completions." + autonomyClause
};

for (const [filename, content] of Object.entries(prompts)) {
  const cleanContent = content.replace(/\n/g, ' ').replace(/\r/g, '');
  fs.writeFileSync(path.join(dir, filename), cleanContent, 'utf8');
}
console.log('Detailed autonomous prompts created successfully.');
